import { Category } from '../../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-maternity',
    name: 'Maternity Essentials',
    slug: 'maternity-essentials',
    description: 'Supportive maternity belts, pregnancy pillows, nursing gowns, and post-partum recovery essentials.',
    image_url: 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&w=600&q=80',
    icon: 'HeartHandshake',
    is_active: true,
    display_order: 1,
  },
  {
    id: 'cat-baby-essentials',
    name: 'Baby Essentials',
    slug: 'baby-essentials',
    description: 'Newborn starter hampers, soft swaddles, hooded bath towels, bibs, scratch mittens, and hospital bag necessities.',
    image_url: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=600&q=80',
    icon: 'Package',
    is_active: true,
    display_order: 2,
  },
  {
    id: 'cat-clothing',
    name: 'Baby Clothing / Fashion',
    slug: 'baby-clothing',
    description: '100% pure organic cotton rompers, party wear, sleepsuits, knit cardigans, and seasonal outfits.',
    image_url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=600&q=80',
    icon: 'Shirt',
    is_active: true,
    display_order: 3,
  },
  {
    id: 'cat-gear',
    name: 'Baby Gear',
    slug: 'baby-gear',
    description: 'Ergonomic baby carriers, compact folding strollers, convertible high chairs, bouncers, and cots.',
    image_url: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=600&q=80',
    icon: 'Compass',
    is_active: true,
    display_order: 4,
  },
  {
    id: 'cat-feeding',
    name: 'Feeding & Nursing',
    slug: 'feeding-nursing',
    description: 'Anti-colic feeding bottles, electric & manual breast pumps, sterilizers, silicone suction tableware, and cups.',
    image_url: 'https://images.unsplash.com/photo-1591522810850-58128c5fb089?auto=format&fit=crop&w=600&q=80',
    icon: 'Milk',
    is_active: true,
    display_order: 5,
  },
  {
    id: 'cat-care',
    name: 'Baby Care',
    slug: 'baby-care',
    description: 'Gentle tear-free shampoos, natural soothing balms, electric nail trimmers, soft comb brushes, and bath sets.',
    image_url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=600&q=80',
    icon: 'Sparkles',
    is_active: true,
    display_order: 6,
  },
  {
    id: 'cat-mothercare',
    name: 'Mother Care',
    slug: 'mother-care',
    description: 'Postpartum peri bottles, organic stretch mark oils, disposable nursing pads, lactation teas, and belly wraps.',
    image_url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
    icon: 'Flower2',
    is_active: true,
    display_order: 7,
  },
  {
    id: 'cat-backtoschool',
    name: 'Back to School',
    slug: 'back-to-school',
    description: 'Ergonomic school backpacks, insulated leakproof bento lunchboxes, stainless water bottles, and durable shoes.',
    image_url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80',
    icon: 'GraduationCap',
    is_active: true,
    display_order: 8,
  },
  {
    id: 'cat-accessories',
    name: 'Baby Accessories',
    slug: 'baby-accessories',
    description: 'Gold-accented pacifier clips, sensory silicone teethers, floral headbands, anti-UV baby sunglasses, and socks.',
    image_url: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=600&q=80',
    icon: 'Sparkle',
    is_active: true,
    display_order: 9,
  },
];
